'use client'

import { useState } from 'react'
import { ArrowRight, BarChart3, CircleDollarSign, CircleHelp, Search } from 'lucide-react'

type TabId = 'about' | 'data' | 'simulator'
type Audience = 'Engenharia' | 'Economia' | 'Público Geral'

type Study = { audience: Audience; title: string; level?: string; summary: string }

const tabs = [
  { id: 'about' as const, label: 'Quem Somos', icon: CircleHelp },
  { id: 'data' as const, label: 'Pesquisas e Dados', icon: BarChart3 },
  { id: 'simulator' as const, label: 'Simulador Gameficado', icon: CircleDollarSign },
]

function curveY(hour: number) { return 10 + 28 * Math.exp(-((hour - 10.5) ** 2) / 24) }
function getReactorCount(hour: number) { return Math.round(12 + 155 * Math.exp(-((hour - 12) ** 2) / 28)) }

function BrandMark() {
  return <span className="flex items-center gap-1.5" aria-label="PoliVSR"><svg viewBox="0 0 28 28" className="size-7 skew-x-[-15deg]" role="img" aria-label="Marca PoliVSR"><ellipse cx="7" cy="14" rx="3.2" ry="10" fill="none" stroke="currentColor" strokeWidth="3" /><ellipse cx="14" cy="14" rx="3.2" ry="10" fill="none" stroke="currentColor" strokeWidth="3" /><ellipse cx="21" cy="14" rx="3.2" ry="10" fill="none" stroke="currentColor" strokeWidth="3" /></svg><span className="text-[1.35rem] font-extrabold tracking-[-.06em]">Poli<span className="text-[#e60000]">VSR</span></span></span>
}

function CurveChart({ hour, onChange }: { hour: number; onChange: (hour: number) => void }) {
  const markerX = 4 + (hour / 24) * 92
  const markerY = curveY(hour)
  const points = Array.from({ length: 25 }, (_, index) => `${4 + (index / 24) * 92},${curveY(index)}`).join(' ')
  return <div className="relative w-full max-w-5xl" aria-label="Gráfico interativo da curva de pato" role="group"><svg viewBox="0 0 100 46" className="h-auto w-full overflow-visible" aria-hidden="true"><defs><linearGradient id="curve-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#e60000" stopOpacity=".48" /><stop offset="1" stopColor="#e60000" stopOpacity="0" /></linearGradient><linearGradient id="curve-stroke"><stop stopColor="#ff7777" /><stop offset=".5" stopColor="#e60000" /><stop offset="1" stopColor="#ff7777" /></linearGradient></defs><path d="M4 10H96M4 24H96M4 38H96" stroke="white" strokeOpacity=".1" strokeWidth=".25" /><polygon points={`4,${curveY(0)} ${points} 96,42 4,42`} fill="url(#curve-fill)" /><polyline points={points} fill="none" stroke="url(#curve-stroke)" strokeWidth=".85" vectorEffect="non-scaling-stroke" /><line x1={markerX} x2={markerX} y1="5" y2="42" stroke="white" strokeOpacity=".8" strokeDasharray="1 1" strokeWidth=".35" /><circle cx={markerX} cy={markerY} r="1.6" fill="#e60000" stroke="white" strokeWidth=".55" /></svg><input aria-label="Hora do dia" type="range" min="0" max="24" step="1" value={hour} onChange={event => onChange(Number(event.target.value))} className="absolute inset-x-0 top-1/2 z-10 h-32 w-full -translate-y-1/2 cursor-pointer touch-none opacity-0" /><div className="mt-2 flex justify-between text-[10px] font-bold uppercase tracking-[.18em] text-slate-500"><span>00h</span><span>Curva de pato · {String(hour).padStart(2, '0')}h</span><span>24h</span></div></div>
}

const blocks = [
  ['Quem somos', 'Somos um grupo de pesquisa formado por alunos de Iniciação Científica (ICs) e Mestrandos da Poli-USP, atuando em parceria direta com a comissão de P&D da Hitachi Energy e grandes transmissoras. Nossa missão é transformar conhecimento acadêmico em soluções aplicáveis para o Sistema Interligado Nacional (SIN). Com a expansão das linhas e o crescimento das fontes renováveis intermitentes, a dinâmica do grid mudou: a demanda varia, a tensão dispara e os equipamentos precisam responder com precisão. O PoliVSR nasce para viabilizar essa transição para uma rede flexível e resiliente.'],
  ['O que estamos fazendo', 'Conduzimos pesquisas aplicadas para quantificar os benefícios do Reator de Derivação Variável (VSR). Nosso foco é demonstrar, com dados medidos, como essa tecnologia resolve os desafios sistêmicos que a rede enfrenta com a queda de carga diurna. Este site é um repositório técnico aberto, permitindo que o setor acompanhe a validação da tecnologia e se junte a nós na próxima evolução do sistema.'],
  ['O que queremos', 'Acreditamos na aliança entre a universidade e a indústria para acelerar a inovação. Queremos atrair concessionárias de transmissão para estudos práticos, comprovando a drástica redução nos custos operacionais (OPEX) e no desgaste de ativos. A meta final é fornecer ao ONS e à EPE embasamento técnico para especificar o VSR nos próximos leilões. A tecnologia já está disponível para produção local no HUB da Hitachi em Guarulhos; nossa missão é provar que essa é a melhor decisão de investimento.'],
  ['O que é o VSR e por que ele é superior?', 'Hoje, a rede utiliza reatores fixos operando como interruptores brutos. Para controlar a tensão, realizam-se manobras agressivas de disjuntor, diminuindo a vida útil do equipamento e gerando restrições operativas. O Variable Shunt Reactor (VSR) funciona como um dimmer. Equipado com um comutador sob carga (OLTC), ele altera o número de espiras ativas em pequenos degraus automáticos, ajustando a absorção de potência reativa sem desconectar o ativo. Isso estabiliza a rede e viabiliza a integração de energias renováveis.'],
] as const

function PageEndNavigation({ activeTab, onNavigate }: { activeTab: TabId; onNavigate: (tab: TabId) => void }) {
  const availableTabs = tabs.filter(tab => tab.id !== activeTab)
  return <nav className="border-t border-slate-200 bg-white px-6 py-12" aria-label="Explorar outras páginas"><div className="mx-auto flex max-w-5xl flex-col items-center gap-5 sm:flex-row sm:justify-center sm:gap-8">{availableTabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} onClick={() => onNavigate(tab.id)} className="flex items-center gap-2 rounded px-4 py-3 text-sm font-bold text-slate-600 transition hover:bg-slate-100 hover:text-[#e60000]"><Icon aria-hidden="true" />{tab.label}</button> })}</div></nav>
}

function Hero({ onNavigate }: { onNavigate: (tab: TabId) => void }) {
  const [hour, setHour] = useState(13)
  const reactors = getReactorCount(hour)
  const maneuvers = Math.round(18 + hour * 1.9)
  return <><section className="bg-slate-950 px-5 pb-20 pt-32 text-left text-white sm:px-8 sm:pt-40"><div className="mx-auto flex max-w-6xl flex-col items-start"><p className="mb-5 self-center text-center text-xs font-bold uppercase tracking-[.3em] text-red-400">PoliVSR · pesquisa aplicada</p><p className="text-2xl font-medium sm:text-3xl">Nesse momento,</p><h1 className="my-2 text-6xl font-black leading-none tracking-[-.07em] text-[#e60000] sm:text-8xl lg:text-[9rem]">{maneuvers} Manobras</h1><p className="text-2xl font-medium sm:text-3xl">foram feitas em todo o país.</p><p className="mt-7 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">{reactors} reatores fixos estão ligados no SIN apenas para dar conta da baixa tensão gerada pela sobra de reativo.</p><div className="mt-14 w-full"><CurveChart hour={hour} onChange={setHour} /></div><p className="mt-8 text-sm text-slate-400 sm:text-base">Arraste sobre a curva para acompanhar a operação ao longo do dia.</p></div></section><section id="about-project" className="border-t border-slate-200 bg-white px-6 py-24"><div className="mx-auto max-w-5xl"><p className="mb-4 text-xs font-bold uppercase tracking-[.25em] text-red-600">O projeto PoliVSR</p><h2 className="text-4xl font-black tracking-tight sm:text-6xl">Da pesquisa aplicada à rede do futuro.</h2><div className="mt-16 divide-y divide-slate-200">{blocks.map(([title, text], index) => <article key={title} className={`grid gap-6 py-12 md:grid-cols-[.8fr_1.4fr] ${index % 2 ? 'bg-slate-50' : 'bg-white'}`}><h3 className="text-2xl font-bold">{title}</h3><p className="text-lg leading-8 text-slate-600">{text}</p></article>)}</div></div></section><PageEndNavigation activeTab="about" onNavigate={onNavigate} /><ContactSection /></>
}

function ContactSection() { return <section className="bg-gray-950 px-6 py-24 text-white"><div className="mx-auto max-w-5xl"><h2 className="mb-4 text-4xl font-bold">Traga a estabilidade do VSR para a sua concessão.</h2><p className="mb-12 max-w-3xl text-lg text-gray-400">O PoliVSR está de portas abertas para novas parcerias de P&amp;D. Se a sua transmissora enfrenta altos custos com desgaste de disjuntores e sobretensões diárias durante a carga leve, junte-se a nós para um estudo de viabilidade técnica e financeira.</p><div className="grid grid-cols-1 gap-12 md:grid-cols-2"><div className="flex flex-col gap-6 text-gray-300"><p><strong className="text-white">Email:</strong> parcerias@polivsr.usp.br</p><p><strong className="text-white">Telefone:</strong> +55 (11) 3091-0000</p><p><strong className="text-white">Pesquisa Aplicada:</strong> Poli-USP, São Paulo - SP</p><p><strong className="text-white">Engenharia e Produção:</strong> Hitachi Energy HUB, Guarulhos - SP</p></div><form className="flex flex-col gap-4"><input className="rounded border border-gray-700 bg-gray-900 p-3 text-white" placeholder="Nome completo" /><input className="rounded border border-gray-700 bg-gray-900 p-3 text-white" placeholder="Empresa (Concessionária / Agente)" /><input className="rounded border border-gray-700 bg-gray-900 p-3 text-white" placeholder="E-mail corporativo" type="email" /><textarea className="h-32 rounded border border-gray-700 bg-gray-900 p-3 text-white" placeholder="Como as sobretensões afetam o OPEX da sua operação hoje?" /><button type="button" className="rounded bg-red-600 p-4 text-center font-bold hover:bg-red-700">Solicitar Estudo de Viabilidade</button></form></div></div></section> }

const audienceDescriptions: Record<Audience, string> = { 'Público Geral': 'Textos explicativos e didáticos sobre a tecnologia VSR e o funcionamento do sistema elétrico. Conteúdo formatado sem jargões para facilitar o primeiro contato com a nossa pesquisa.', Engenharia: 'Pesquisas acadêmicas e estudos de engenharia sobre os impactos na confiabilidade e controle dinâmico do grid. Acompanhe os avanços técnicos da substituição de reatores fixos por modelos de derivação variável.', Economia: 'Estudos sobre os impactos financeiros, redução de OPEX e viabilidade de mercado. Direcionado a concessionárias e investidores que buscam entender o custo-benefício e o retorno financeiro da tecnologia.' }

const studies: Study[] = [
  { audience: 'Público Geral', title: 'Entenda o Efeito Ferranti na Prática', summary: 'Por que a tensão sobe perigosamente quando o consumo do país cai durante o dia.' },
  { audience: 'Público Geral', title: 'O que é a Curva de Pato?', summary: 'Como os painéis solares mudaram o comportamento do Sistema Interligado Nacional.' },
  { audience: 'Público Geral', title: 'Interruptor vs. Dimmer', summary: 'A diferença fundamental entre o reator fixo e a regulação suave do VSR.' },
  { audience: 'Engenharia', title: 'Análise de Sobretensões em Regime Permanente no SIN', level: 'Mestrado', summary: 'Mapeamento das regiões Norte e Nordeste em condições de carga mínima.' },
  { audience: 'Engenharia', title: 'Impacto das Manobras na Vida Útil de Disjuntores de 500 kV', level: 'IC', summary: 'Quantificação do desgaste mecânico e elétrico causado pelo chaveamento constante.' },
  { audience: 'Engenharia', title: 'Controle Dinâmico Lento e o uso de OLTC em Reatores', level: 'Doutorado', summary: 'Modelagem do comportamento do comutador de derivação para estabilidade de tensão.' },
  { audience: 'Economia', title: 'Calculadora de Payback: CAPEX vs OPEX do VSR', level: 'Mestrado', summary: 'Comparativo financeiro da adoção da tecnologia frente aos custos de manutenção de longo prazo.' },
  { audience: 'Economia', title: 'Custos Operacionais Invisíveis da Rigidez do Grid', level: 'IC', summary: 'O preço real que as transmissoras pagam pela limitação dos reatores fixos atuais.' },
  { audience: 'Economia', title: 'Transferência de Tecnologia (ToT) e a Produção Nacional', level: 'P&D', summary: 'Estudo sobre a viabilidade industrial do VSR no HUB da Hitachi Energy em Guarulhos.' },
]

function ArticleView({ article, onBack, onSelect, onNavigate }: { article: Study; onBack: () => void; onSelect: (article: Study) => void; onNavigate: (tab: TabId) => void }) {
  const related = studies.filter(study => study.audience === article.audience && study.title !== article.title).slice(0, 2)
  return <section className="min-h-screen bg-white px-6 pb-24 pt-32 text-gray-900 sm:px-10"><div className="mx-auto max-w-5xl"><button onClick={onBack} className="mb-14 text-sm font-bold text-[#e60000] hover:underline">← Voltar para Pesquisas</button><header className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-gray-400">{article.audience}</p><h1 className="mt-4 text-4xl font-black leading-tight sm:text-6xl">{article.title}</h1>{article.level && <span className="mt-6 inline-flex rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">{article.level}</span>}<p className="mt-5 text-sm text-gray-500">Última atualização: 15 de Outubro de 2026</p></header><article className="mx-auto mt-14 max-w-3xl text-lg leading-relaxed text-gray-700"><p>{article.summary} Este estudo apresenta uma leitura aprofundada dos dados operacionais e dos impactos da tecnologia VSR no sistema elétrico brasileiro.</p><p className="mt-7">A pesquisa combina modelagem, medições e análise de cenários para transformar evidências técnicas em decisões mais seguras. Os resultados ajudam a compreender como a regulação variável pode reduzir manobras, preservar ativos e ampliar a flexibilidade do grid.</p><p className="mt-7">Ao aproximar universidade, indústria e agentes de transmissão, o PoliVSR cria uma base pública para a evolução do sistema. Novos dados serão incorporados conforme os estudos avancem.</p><button className="mt-12 rounded bg-red-600 px-6 py-4 text-base font-bold text-white hover:bg-red-700">Acessar Publicação Oficial</button></article><div className="mx-auto mt-24 max-w-3xl border-t border-gray-200 pt-10"><h2 className="text-2xl font-bold">Artigos Relacionados</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{related.map(item => <button key={item.title} onClick={() => onSelect(item)} className="rounded border border-gray-200 p-5 text-left transition hover:border-red-600 hover:shadow-[0_0_20px_rgba(230,0,0,0.3)]"><span className="text-sm font-bold text-red-600">{item.audience}</span><p className="mt-2 font-bold">{item.title}</p></button>)}</div></div></div></section>
}

function DataPage({ onNavigate }: { onNavigate: (tab: TabId) => void }) {
  const [activeAudience, setActiveAudience] = useState<Audience>('Engenharia')
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedArticle, setSelectedArticle] = useState<Study | null>(null)
  if (selectedArticle) return <ArticleView article={selectedArticle} onBack={() => setSelectedArticle(null)} onNavigate={onNavigate} />
  const visibleStudies = studies.filter(study => study.audience === activeAudience && study.title.toLowerCase().includes(searchQuery.toLowerCase()))
  return <><section className="min-h-screen bg-white px-6 pb-24 pt-32 text-gray-900 sm:px-10"><div className="mx-auto max-w-6xl"><div className="py-10 text-center sm:py-16"><p className="text-xs font-bold uppercase tracking-[.3em] text-[#e60000]">Repositório público</p><h1 className="mt-4 text-5xl font-black tracking-tight sm:text-7xl">Pesquisas e dados.</h1><div className="relative mx-auto mt-10 w-full max-w-2xl"><label htmlFor="study-search" className="sr-only">Buscar pesquisa</label><input id="study-search" value={searchQuery} onChange={event => setSearchQuery(event.target.value)} placeholder="Busque pelo nome da pesquisa..." className="w-full rounded border border-gray-200 bg-white py-4 pl-12 pr-5 text-base shadow-sm outline-none transition focus:border-[#e60000] focus:ring-2 focus:ring-red-100" /><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-400" aria-hidden="true" /></div><div className="mt-8 flex flex-wrap justify-center gap-2" role="tablist" aria-label="Filtrar pesquisas por público">{(['Engenharia', 'Economia', 'Público Geral'] as Audience[]).map(audience => <button key={audience} role="tab" aria-selected={activeAudience === audience} onClick={() => setActiveAudience(audience)} className={`rounded px-5 py-3 text-sm font-bold transition ${activeAudience === audience ? 'bg-gray-900 text-white' : 'bg-gray-100 text-gray-700 hover:bg-gray-200'}`}>{audience}</button>)}</div><p className="mx-auto mt-8 max-w-3xl rounded bg-gray-50 p-6 text-center text-sm leading-7 text-gray-700 sm:text-base">{audienceDescriptions[activeAudience]}</p></div><div className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">{visibleStudies.map(study => <button key={study.title} onClick={() => setSelectedArticle(study)} className="flex min-h-64 cursor-pointer flex-col rounded border border-gray-200 bg-white p-6 text-left shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-red-600 hover:shadow-[0_0_20px_rgba(230,0,0,0.3)]">{study.level && <span className="w-fit rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-red-700">{study.level}</span>}<h2 className="mt-5 text-xl font-bold leading-snug">{study.title}</h2><p className="mt-3 flex-1 text-sm leading-6 text-gray-600">{study.summary}</p><span className="mt-5 self-end text-sm font-bold text-red-600">Ler estudo →</span></button>)}</div>{visibleStudies.length === 0 && <p className="py-20 text-center text-gray-500">Nenhuma pesquisa encontrada.</p>}</div></section></>
}

function Placeholder({ onNavigate }: { onNavigate: (tab: TabId) => void }) { return <><div className="mx-auto flex min-h-screen max-w-4xl flex-col items-center justify-center px-6 text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-red-600">Módulo em desenvolvimento</p><h1 className="mt-4 text-5xl font-extrabold">Simulador Gameficado</h1></div></> }

export default function Page() {
  const [activeTab, setActiveTab] = useState<TabId>('about')
  return <main className="min-h-screen bg-white text-slate-950"><header className="fixed inset-x-0 top-0 z-20 border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-7xl items-center gap-8 px-6 sm:px-10 lg:px-16"><button onClick={() => setActiveTab('about')} aria-label="Ir para o início"><BrandMark /></button><nav className="hidden items-center gap-8 md:flex" aria-label="Navegação principal">{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`flex items-center gap-2 border-b-2 px-1 py-7 text-sm font-bold ${activeTab === tab.id ? 'border-[#e60000] text-slate-950' : 'border-transparent text-slate-500 hover:text-slate-900'}`}><Icon data-icon="inline-start" />{tab.label}</button> })}</nav><nav className="ml-auto flex items-center gap-1 md:hidden" aria-label="Navegação principal mobile">{tabs.map(tab => { const Icon = tab.icon; return <button key={tab.id} onClick={() => setActiveTab(tab.id)} aria-label={tab.label} aria-current={activeTab === tab.id ? 'page' : undefined} title={tab.label} className={`flex size-11 items-center justify-center rounded-full transition-colors ${activeTab === tab.id ? 'bg-slate-950 text-white' : 'text-slate-500 hover:bg-slate-100 hover:text-slate-950'}`}><Icon aria-hidden="true" /></button> })}</nav></div></header>{activeTab === 'about' ? <Hero onNavigate={setActiveTab} /> : activeTab === 'data' ? <DataPage onNavigate={setActiveTab} /> : <Placeholder onNavigate={setActiveTab} />}</main>
}
